kind: ImageStream
apiVersion: v1
metadata:
  name: openjdk
spec:
  tags:
  - from:
      kind: DockerImage
      name: 'openjdk:8-jre-alpine'
    name: 8-jre-alpine
---
kind: ImageStream
apiVersion: v1
metadata:
  name: openjdk-custom
---
kind: BuildConfig
apiVersion: v1
metadata:
  name: openjdk-custom-build
spec:
  source:
    type: Git
    git:
      uri: https://github.com/strimzi/strimzi-lab
  strategy:
    type: docker
    dockerStrategy:
      dockerfilePath: iot-demo/device-app/resources/openjdk-custom.Dockerfile
      from:
        kind: ImageStreamTag
        name: openjdk:8-jre-alpine
  output:
    to:
      kind: ImageStreamTag
      name: openjdk-custom:latest
---
kind: BuildConfig
apiVersion: v1
metadata:
  name: device-app-build
spec:
  source:
    type: Git
    git:
      uri: https://github.com/strimzi/strimzi-lab
    contextDir: iot-demo/device-app
  strategy:
    type: source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: openjdk-custom:latest