- hosts: localhost
  name: Kafka Zero to Hero Workshop
  vars:
    server: https://api.cluster-6x8wc.6x8wc.sandbox773.opentlc.com:6443
    kafka_cluster: my-cluster
    grafana_user: admin
    grafana_password: admin
    insecure_skip_tls_verify: true
    delete_workshop: false
    ocp_username: admin
    debug_enable: false
    num_users: 1
    
    # USER REGISTRATION 
    registration_namespace: registration
    snapshot_operator_project: openshift-marketplace
    lab_title: "Kafka Zero to Hero Workshop"
    username_prefix: "user"
    user_access_token: "openshift"

    # CHE configuration
    devspace_project: devspace

    # provision_webapp
    solution_explorer_client_id: tutorial-web-app
    solution_explorer_image_tag: '1.0.10'
    solution_explorer_image: 'quay.io/gcamposo/tutorial-web-app:{{ solution_explorer_image_tag }}'
    solution_explorer_namespace: "workshop-solution-explorer"
    solution_explorer_walkthrough_locations: https://github.com/hodrigohamalho/kafka-zero-to-hero?walkthroughsFolder=/labs#master

  tasks:
    - name: Define domain
      set_fact:
        domain : "{{ server | regex_replace('https://api.') | regex_replace(':6443') }}"

    - name: Set route_subdomain
      set_fact:
        route_subdomain: "apps.{{ domain }}"

    - name: Set console_url
      set_fact:
        console_url: "https://console-openshift-console.{{ route_subdomain }}"

    - name: Log in as super user with token on OpenShift 4
      command: "oc login --token={{ tkn }}  --server={{ server }} --insecure-skip-tls-verify={{ insecure_skip_tls_verify }}"
      when:
       - token is defined
       - token is not none
       - token|trim() != ""
      ignore_errors: no

    # - name: Include Solution Explorer Role
    #   include_role:
    #     name: solution-explorer
    #   when: not delete_workshop

    # - name: Include Username Distribution
    #   when:
    #     - num_users | int > 0
    #     - not delete_workshop
    #   include_role:
    #     name: username-distribution
    
    - name: Provision OpenShift Dev Spaces
      include_role:
        name: devspaces
      vars:
        operators_project: "openshift-operators"
        snapshot_operator_project: "openshift-marketplace"

    # - name: output workshop info
    #   msg: "{{ item }}"
    #   loop:
    #     - ""
    #     - "Kafka Zero to Hero - {{ lab_title }} provisioned for {{ num_users }} user(s)"
    #     - ""
    #     - "User Registration: https://users-registration.{{ route_subdomain }}"
    #     - "Access Token for registration is '{{ user_access_token }}'"
    #     - "Admin credentials for registration app are 'admin/{{ workshop_registration_admin_password }}'"
    #     - "You should share this URL (or a shortlink for it) -- It is all they will need to get started!"
    #     - ""
    #     - "Solution Explorer: "
    #     - "https://tutorial-web-app-webapp.{{ route_subdomain }}"
    #     - ""
    #     - "OpenShift Console: {{ console_url }}"
    #     - "Cluster admin login with '{{ ocp_username }}' / 'r3dh4t1!'"
    #   when: not silent|bool

    